CREATE TABLE Groups
(
ID INT CONSTRAINT PK_Group PRIMARY KEY,
ID_Specialty INT CONSTRAINT FK_Group_Specialty FOREIGN KEY REFERENCES Specialties(ID),
GroupName NVARCHAR(5) CONSTRAINT UQ_Groups_GroupName NOT NULL,
Course INT NOT NULL
);